n = int(input("Um número:"))
print(f'{n}*0=0'
      f'\n{n}*1={n * 1}'
      f'\n{n}*2={n * 2}'
      f'\n{n}*3={n * 3}'
      f'\n{n}*4={n * 4}'
      f'\n{n}*5={n * 5}'
      f'\n{n}*6={n * 6}'
      f'\n{n}*7={n * 7}'
      f'\n{n}*8={n * 8}'
      f'\n{n}*9={n * 9}'
      f'\n{n}*10={n * 10}')